# ratgdo for ESPHome
# https://github.com/ratgdo/esphome-ratgdo

substitutions:
  id_prefix: garage_door_ratgdo_east
  friendly_name: Garage-Door RATGDO East
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

esphome:
  name: ${id_prefix}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: ratgdo.esphome
    version: '2.5'

esp8266:
  board: d1_mini
  restore_from_flash: true

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key06

# Enable over-the-air updates.
ota:
  platform: esphome
  password: !secret ota_password04

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

# Connect to WiFi.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_hotspot_password

# Enable Web server.
web_server:
#  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# allows you to configure your ESPHome device via a serial connection.
#improv_serial:

#captive_portal:
#  ssid: "My Captive Portal"
#  password: "12345678"
#  redirect_url: "https://www.example.com/"
